pref("extensions.rh.version",0);
pref("extensions.rh.firststart", true);
pref("extensions.rh.endzeit", false);
pref("extensions.rh.geldsumme", false);
pref("extensions.rh.produktion", false);
pref("extensions.rh.umsatzverkauf", false);
pref("extensions.rh.umsatzlager", false);
pref("extensions.rh.countdown", true);
pref("extensions.rh.autoquell", false);
pref("extensions.rh.aqv","125000");
pref("extensions.rh.geldverkauf",false);
pref("extensions.rh.wbwlink",false);
pref("extensions.rh.guildpage",false);
pref("extensions.rh.ptitle",false);
pref("extensions.rh.ptv","Production");
pref("extensions.rh.taschenrechner", false);
pref("extensions.rh.ausgabenmarkt", false);
pref("extensions.rh.allewaren", false);
pref("extensions.rh.ausbau", false);
pref("extensions.rh.gesamtwert", false);
pref("extensions.rh.sortierung", 1);
pref("extensions.rh.welt", 0);
pref("extensions.rh.schnellzugriff", false);
pref("extensions.rh.vertragskip", false);
pref("extensions.rh.marktskip", false);
pref("extensions.rh.prodskip", false);
pref("extensions.rh.cancelskip", false);
pref("extensions.rh.firmensuche", false);
pref("extensions.rh.sortadress", false);
pref("extensions.rh.nachrichtskip", false);
pref("extensions.rh.forschend", false);
pref("extensions.rh.gebfast", false);
pref("extensions.rh.gebover", false);
pref("extensions.rh.wb", false);
pref("extensions.rh.zeiten", "5:1:6:24:");
pref("extensions.rh.farben", "007f00:00007f:7f0000:000000:");
pref("extensions.rh.geb2sort", 0);
pref("extensions.rh.notizcontent", "");
pref("extensions.rh.nbopac", 90);
pref("extensions.rh.notizbuch", false);
pref("extensions.rh.todo", false);
pref("extensions.rh.verwaltsort", false);
pref("extensions.rh.statsakt", false);
pref("extensions.rh.statsdiff", false);
pref("extensions.rh.statscol", false);
pref("extensions.rh.statsverkaufcol", false);
pref("extensions.rh.grphverk", false);
pref("extensions.rh.grphstat", false);
pref("extensions.rh.grphaut", false);
pref("extensions.rh.grph1",0);
pref("extensions.rh.grph2",1);
pref("extensions.rh.verwaltbereit", false);
pref("extensions.rh.menupreis", false);
pref("extensions.rh.spqchoose", false);
pref("extensions.rh.vkpremium", false);
pref("extensions.rh.nbcols",50);
pref("extensions.rh.nbrows",10);
pref("extensions.rh.igmmarkt", false);
pref("extensions.rh.igmfax", false);
pref("extensions.rh.igmadress", false);
pref("extensions.rh.igmvertrag", false);
pref("extensions.rh.sigvorakt", false);
pref("extensions.rh.signachakt", false);
pref("extensions.rh.sigvor", "Guten Tag %firma%,");
pref("extensions.rh.signach", "Viele Grüße\n%name%");
pref("extensions.rh.verwq",127);
pref("extensions.rh.saveq", false);
pref("extensions.rh.sortvertrag", false);
pref("extensions.rh.alleverk", false);
pref("extensions.rh.tracking", false);
pref("extensions.rh.nolinkicon", false);
